[platform.windows.env]
TFLITEC_PREBUILT_PATH={value="src\\takeflight_computer_vision\\3rd_party\\tensorflowlite_c.dll", relative=true}
[env]
TFLITEC_PREBUILT_PATH={value="/usr/lib/libtensorflowlite_c.so"} # According to FHS convention. *May not work for Nix