[env]
TFLITEC_PREBUILT_PATH_X86_64_PC_WINDOWS_MSVC={value="src\\takeflight_computer_vision\\3rd_party\\tensorflowlite_c.dll", relative=true}
TFLITEC_PREBUILT_PATH_X86_64_UNKNOWN_LINUX_GNU={value="src/takeflight_computer_vision/3rd_party/libtensorflowlite_c.so", relative=true}